/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig2;

public class int_array_stats_alert_num_channels {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected int_array_stats_alert_num_channels(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(int_array_stats_alert_num_channels obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_int_array_stats_alert_num_channels(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int_array_stats_alert_num_channels() {
    this(libtorrent_jni.new_int_array_stats_alert_num_channels__SWIG_0(), true);
  }

  public int_array_stats_alert_num_channels(int_array_stats_alert_num_channels other) {
    this(libtorrent_jni.new_int_array_stats_alert_num_channels__SWIG_1(int_array_stats_alert_num_channels.getCPtr(other), other), true);
  }

  public long size() {
    return libtorrent_jni.int_array_stats_alert_num_channels_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return libtorrent_jni.int_array_stats_alert_num_channels_isEmpty(swigCPtr, this);
  }

  public void fill(int u) {
    libtorrent_jni.int_array_stats_alert_num_channels_fill(swigCPtr, this, u);
  }

  public int get(int i) {
    return libtorrent_jni.int_array_stats_alert_num_channels_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    libtorrent_jni.int_array_stats_alert_num_channels_set(swigCPtr, this, i, val);
  }

}
