/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig2;

public class save_state_flags_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected save_state_flags_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(save_state_flags_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_save_state_flags_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static save_state_flags_t all() {
    return new save_state_flags_t(libtorrent_jni.save_state_flags_t_all(), true);
  }

  public boolean op_bool() {
    return libtorrent_jni.save_state_flags_t_op_bool(swigCPtr, this);
  }

  public boolean op_eq(save_state_flags_t f) {
    return libtorrent_jni.save_state_flags_t_op_eq(swigCPtr, this, save_state_flags_t.getCPtr(f), f);
  }

  public boolean op_ne(save_state_flags_t f) {
    return libtorrent_jni.save_state_flags_t_op_ne(swigCPtr, this, save_state_flags_t.getCPtr(f), f);
  }

  public save_state_flags_t op_or(save_state_flags_t other) {
    return new save_state_flags_t(libtorrent_jni.save_state_flags_t_op_or(swigCPtr, this, save_state_flags_t.getCPtr(other), other), true);
  }

  public save_state_flags_t op_and(save_state_flags_t other) {
    return new save_state_flags_t(libtorrent_jni.save_state_flags_t_op_and(swigCPtr, this, save_state_flags_t.getCPtr(other), other), true);
  }

  public save_state_flags_t xor(save_state_flags_t other) {
    return new save_state_flags_t(libtorrent_jni.save_state_flags_t_xor(swigCPtr, this, save_state_flags_t.getCPtr(other), other), true);
  }

  public save_state_flags_t inv() {
    return new save_state_flags_t(libtorrent_jni.save_state_flags_t_inv(swigCPtr, this), true);
  }

  public int to_int() {
    return libtorrent_jni.save_state_flags_t_to_int(swigCPtr, this);
  }

  public save_state_flags_t() {
    this(libtorrent_jni.new_save_state_flags_t(), true);
  }

}
