/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig;

public class int_byte_pair_vector extends java.util.AbstractList<int_byte_pair> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected int_byte_pair_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(int_byte_pair_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_int_byte_pair_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int_byte_pair_vector(int_byte_pair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (int_byte_pair element : initialElements) {
      add(element);
    }
  }

  public int_byte_pair_vector(Iterable<int_byte_pair> initialElements) {
    this();
    for (int_byte_pair element : initialElements) {
      add(element);
    }
  }

  public int_byte_pair get(int index) {
    return doGet(index);
  }

  public int_byte_pair set(int index, int_byte_pair e) {
    return doSet(index, e);
  }

  public boolean add(int_byte_pair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, int_byte_pair e) {
    modCount++;
    doAdd(index, e);
  }

  public int_byte_pair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int_byte_pair_vector() {
    this(libtorrent_jni.new_int_byte_pair_vector__SWIG_0(), true);
  }

  public int_byte_pair_vector(int_byte_pair_vector other) {
    this(libtorrent_jni.new_int_byte_pair_vector__SWIG_1(int_byte_pair_vector.getCPtr(other), other), true);
  }

  public long capacity() {
    return libtorrent_jni.int_byte_pair_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtorrent_jni.int_byte_pair_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtorrent_jni.int_byte_pair_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtorrent_jni.int_byte_pair_vector_clear(swigCPtr, this);
  }

  public int_byte_pair_vector(int count, int_byte_pair value) {
    this(libtorrent_jni.new_int_byte_pair_vector__SWIG_2(count, int_byte_pair.getCPtr(value), value), true);
  }

  private int doSize() {
    return libtorrent_jni.int_byte_pair_vector_doSize(swigCPtr, this);
  }

  private void doAdd(int_byte_pair x) {
    libtorrent_jni.int_byte_pair_vector_doAdd__SWIG_0(swigCPtr, this, int_byte_pair.getCPtr(x), x);
  }

  private void doAdd(int index, int_byte_pair x) {
    libtorrent_jni.int_byte_pair_vector_doAdd__SWIG_1(swigCPtr, this, index, int_byte_pair.getCPtr(x), x);
  }

  private int_byte_pair doRemove(int index) {
    return new int_byte_pair(libtorrent_jni.int_byte_pair_vector_doRemove(swigCPtr, this, index), true);
  }

  private int_byte_pair doGet(int index) {
    return new int_byte_pair(libtorrent_jni.int_byte_pair_vector_doGet(swigCPtr, this, index), false);
  }

  private int_byte_pair doSet(int index, int_byte_pair val) {
    return new int_byte_pair(libtorrent_jni.int_byte_pair_vector_doSet(swigCPtr, this, index, int_byte_pair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    libtorrent_jni.int_byte_pair_vector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
