/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig;

public class list_files_listener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected list_files_listener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(list_files_listener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_list_files_listener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    libtorrent_jni.list_files_listener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    libtorrent_jni.list_files_listener_change_ownership(this, swigCPtr, true);
  }

  public boolean pred(String p) {
    return (getClass() == list_files_listener.class) ? libtorrent_jni.list_files_listener_pred(swigCPtr, this, p) : libtorrent_jni.list_files_listener_predSwigExplicitlist_files_listener(swigCPtr, this, p);
  }

  public list_files_listener() {
    this(libtorrent_jni.new_list_files_listener(), true);
    libtorrent_jni.list_files_listener_director_connect(this, swigCPtr, true, true);
  }

}
