/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig;

public class piece_block_vector extends java.util.AbstractList<piece_block> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected piece_block_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(piece_block_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_piece_block_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public piece_block_vector(piece_block[] initialElements) {
    this();
    reserve(initialElements.length);

    for (piece_block element : initialElements) {
      add(element);
    }
  }

  public piece_block_vector(Iterable<piece_block> initialElements) {
    this();
    for (piece_block element : initialElements) {
      add(element);
    }
  }

  public piece_block get(int index) {
    return doGet(index);
  }

  public piece_block set(int index, piece_block e) {
    return doSet(index, e);
  }

  public boolean add(piece_block e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, piece_block e) {
    modCount++;
    doAdd(index, e);
  }

  public piece_block remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public piece_block_vector() {
    this(libtorrent_jni.new_piece_block_vector__SWIG_0(), true);
  }

  public piece_block_vector(piece_block_vector other) {
    this(libtorrent_jni.new_piece_block_vector__SWIG_1(piece_block_vector.getCPtr(other), other), true);
  }

  public long capacity() {
    return libtorrent_jni.piece_block_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libtorrent_jni.piece_block_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libtorrent_jni.piece_block_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libtorrent_jni.piece_block_vector_clear(swigCPtr, this);
  }

  public piece_block_vector(int count, piece_block value) {
    this(libtorrent_jni.new_piece_block_vector__SWIG_2(count, piece_block.getCPtr(value), value), true);
  }

  private int doSize() {
    return libtorrent_jni.piece_block_vector_doSize(swigCPtr, this);
  }

  private void doAdd(piece_block x) {
    libtorrent_jni.piece_block_vector_doAdd__SWIG_0(swigCPtr, this, piece_block.getCPtr(x), x);
  }

  private void doAdd(int index, piece_block x) {
    libtorrent_jni.piece_block_vector_doAdd__SWIG_1(swigCPtr, this, index, piece_block.getCPtr(x), x);
  }

  private piece_block doRemove(int index) {
    return new piece_block(libtorrent_jni.piece_block_vector_doRemove(swigCPtr, this, index), true);
  }

  private piece_block doGet(int index) {
    return new piece_block(libtorrent_jni.piece_block_vector_doGet(swigCPtr, this, index), false);
  }

  private piece_block doSet(int index, piece_block val) {
    return new piece_block(libtorrent_jni.piece_block_vector_doSet(swigCPtr, this, index, piece_block.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    libtorrent_jni.piece_block_vector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
