/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.libtorrent4j.swig;

public class posix_wrapper {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected posix_wrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(posix_wrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libtorrent_jni.delete_posix_wrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    libtorrent_jni.posix_wrapper_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    libtorrent_jni.posix_wrapper_change_ownership(this, swigCPtr, true);
  }

  public int open(String path, int flags, int mode) {
    return libtorrent_jni.posix_wrapper_open(swigCPtr, this, path, flags, mode);
  }

  public int stat(String path, posix_stat_t buf) {
    return libtorrent_jni.posix_wrapper_stat(swigCPtr, this, path, posix_stat_t.getCPtr(buf), buf);
  }

  public int mkdir(String path, int mode) {
    return libtorrent_jni.posix_wrapper_mkdir(swigCPtr, this, path, mode);
  }

  public int rename(String oldpath, String newpath) {
    return libtorrent_jni.posix_wrapper_rename(swigCPtr, this, oldpath, newpath);
  }

  public int remove(String path) {
    return libtorrent_jni.posix_wrapper_remove(swigCPtr, this, path);
  }

  public posix_wrapper() {
    this(libtorrent_jni.new_posix_wrapper(), true);
    libtorrent_jni.posix_wrapper_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
